---
extends: relaxed

rules:
  line-length:
    max: 150
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  new-lines:
    type: unix
