networks:
  streaming-public:
    external: true
    name: streaming-public
  streaming-private:
    external: true
    name: streaming-private

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://haproxy-postgres:5000/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_HOSTNAME_URL=https://keycloak.duoowatch.com
      - KC_HOSTNAME_ADMIN_URL=https://keycloak.duoowatch.com
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    command: start
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=streaming-public"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.duoowatch.com`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - streaming-public
      - streaming-private
