name: storage

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://keycloak:8080/realms/streaming-lab/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=minio
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
      - MINIO_IDENTITY_OPENID_REDIRECT_URI=https://minio.duoowatch.com/oauth_callback
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=Login with Keycloak
      - MINIO_IDENTITY_OPENID_SCOPES=openid,profile,email
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.duoowatch.com`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.services.minio.loadbalancer.server.port=9001
    networks:
      - storage
      - streaming-net

volumes:
  minio_data:

networks:
  storage:
    name: storage-net
    driver: bridge
  streaming-net:
    external: true
    name: streaming-net
