global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:

  - job_name: vm-principal
    static_configs:
      - targets: ["192.168.10.2:9100"]
        labels:
          instance: vm-principal
          role: streaming

  - job_name: vm-dns
    static_configs:
      - targets: ["192.168.20.2:9100"]
        labels:
          instance: vm-dns
          role: dns

  - job_name: vm-backup
    static_configs:
      - targets: ["192.168.30.2:9100"]
        labels:
          instance: vm-backup
          role: backup
